spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskhub?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: taskhubuser
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${JWT_SECRET:bb9bc6e4baa7cda71b5d50df079f2ad1}
    expiration: 3600000

server:
  port: 8080